steves_twitter_apps/geohash/urls.py
from django.urls import path

from . import views

app_name = 'geohash'

urlpatterns = [
    path('', views.index, name='index'),
    path('CountrySelect/', views.tophash_by_country, name='ByCountry'),
    path('MetroSelect/', views.tophash_by_metro, name='ByMetro'),
    path('m/<name>/', views.tophash_manual, name='tophash_name'),
    path('m/<country>/<name>/', views.tophash_manual, name='tophash'),
    path('m/<country>/', views.tophash_manual, name='tophash_country'),
]

steves_twitter_apps/steves_twitter_apps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('geohash/', include('geohash.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

steves_twitter_apps/geohash/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Woeids(models.Model):
    country = models.CharField(max_length=200, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    woeid = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return '%s %s %s' % (
        self.country,
        self.name,
        str(self.woeid)
        )

steves_twitter_apps/geohash/forms.py
from django import forms
from .models import Woeids


def tuplefy_countries():
    """Query Woeids model for sorted list of countries and reformat into list of tuples
    for consumption by SelectCountry form class.
    """
    q_set = Woeids.objects.values('country').distinct().order_by('country')
    COUNTRIES = []
    for d in q_set:
        for k, v in d.items():
            COUNTRIES.append((v,v))
    return COUNTRIES

class SelectCountry(forms.Form):
    country = forms.ChoiceField(widget=forms.Select, choices=tuplefy_countries())

steves_twitter_apps/geohash/views.py
import json
import numpy as np
import pandas as pd
import os
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse, HttpResponseRedirect
from django.template import loader
from django.template.loader import render_to_string
from django.shortcuts import render
from django.urls import reverse
from django import forms

from .top_bygeo import trending_by_geo
from .models import Woeids
from .forms import SelectCountry


# Create your views here.
def index(request):
    countries = Woeids.objects.values('country').distinct().order_by('country')
    ww = trending_by_geo(woeid=1)
    form = SelectCountry()
    context = {'countries': countries, 'd': ww, 'form':form}
    return render(request, 'geohash/index.html', context)


def tophash_by_country(request):
    """Return results from country entered via the dropdown form on homepage.
    """
    print("LOG 2.0 - request object: {}".format(request))
    print("LOG 2.1 - request.GET object: {}".format(request.GET))
    print("LOG 2.2 - request.GET.country object: {}".format(request.GET['country']))
    country = request.GET['country']
    querySet = (
Woeids.objects.filter(name = country).filter(country = country).values('woeid')
        )
    print("LOG 2.3 - This is the country being passed to the Woeids query: {}"
          .format(country))
    print("LOG 2.4 - This is the querySet being passed to get 'woeid': {}"
          .format(querySet))
    woeid = querySet[0]['woeid']
    top_hashes = trending_by_geo(woeid=woeid)
    
    _NAMES = []
    q_set = (
        Woeids.objects.filter(country=country).values('name').order_by('name')
    )
    for d in q_set:
        for k, v in d.items():
           _NAMES.append((v,v))
    _NAMES.insert(0, ('', ''))
    
    if len(_NAMES) > 1: # Test if metros under countries; _NAMES will always
                        # include country name (hence, test > 1)
        print("LOG 2.5 - Metro Names: {}".format(_NAMES))
        class _SelectMetro(forms.Form):
            metro = forms.ChoiceField(widget=forms.Select, choices=_NAMES)
        form = _SelectMetro()
    else:
        form = None
    
    context = {'country': country, 'form': form, 'd': top_hashes}
    return render(request, "geohash/result.html", context)


def tophash_by_metro(request):
    """Return result from metro entered via dropdown from country results page.
    """
    metro = request.GET['metro']
    querySet = (
        Woeids.objects.filter(name = metro).values('woeid', 'country')
    )
    woeid = querySet[0]['woeid']
    print("LOG 3.1 - woeid: {}".format(woeid))
    country = querySet[0]['country']
    top_hashes = trending_by_geo(woeid=woeid)
    print("LOG 3.2 - top_hashes output: {}".format(top_hashes))
    context = {'name': metro, 'country': country, 'd': top_hashes}
    return render(request, "geohash/result.html", context)


def tophash_manual(request, name='', country=''):
    """ Return results from country and/or name parameters entered manually
    via the address bar of the browser with the '/m/' pattern. 
        E.g. localhost:8000/geohash/m/france/paris
    """
    print("LOG 1.0 - request object: {}".format(request))
    print("LOG 1.1 - request.GET object: {}".format(request.GET))
    country = country.title()
    name = name.title()
    if not country: # For worldwide
        querySet = (
        Woeids.objects.filter(name = name).values('woeid')
        )
    elif not name: # For countries at country grain
        querySet = (
Woeids.objects.filter(name = country).filter(country = country).values('woeid')
        )
    else: # For country, city
        querySet = (
        Woeids.objects.filter(name = name).filter(country = country).values('woeid')
        )
    print("LOG 1.2 - This is the country being passed to the Woeids query: {}"
          .format(country))
    print("LOG 1.3 - This is the querySet being passed to get 'woeid': {}"
          .format(querySet))
    woeid = querySet[0]['woeid']
    top_hashes = trending_by_geo(woeid=woeid)
    context = {'country': country, 'name': name, 'd': top_hashes}
    return render(request, "geohash/result.html", context)

steves_twitter_apps/geohash/templates/geohash/index.html
<h3 style="margin-left:100px">Top Twitter HashTags Trending Now -- WorldWide</h3>

<body>

<form style="margin-left:100px" action="{% url 'geohash:ByCountry' %}" method="get">
  {{ form }}
  <input type="submit" value="Submit">
</form>

{% comment %}
old code
{% if countries %}

<form action={% url "geohash:tophash_country" country %} method="get"> 

<label for="country" style="margin-left:100px">Results by Country</label>
<select id="country">
  {% for c in countries %}
  <option value={{ c.country }} name="country">{{ c.country }}</option>
  {% endfor %}
</select>

<input type="submit" value="Submit">

</form>
{% endif %}
<br>
{% endcomment %}


{% if d %}
<table style="background-color:#c7e1f0; width:350px; margin-top:35px; margin-left:100px" border="1" class="dataframe">
  <thead>
    <tr style="text-align: center;">
      <th>Rank</th>
      <th>HashTag</th>
      <th>TweetVol</th>
    </tr>
  </thead>
  <tbody>
  {% for k, v in d.items %}
  <tr>
    <td>{{ k }}</td>
    <td>{{ v.HashTag }}</td>
    <td style="text-align:right">{{ v.TweetVol }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}
</body>

steves_twitter_apps/geohash/templates/geohash/result.html
{% if name and country %}
<h3 style="margin-left:100px">Top Twitter HashTags Trending Now -- {{ name }}, {{ country }}</h3>
{% elif name and not country %}
<h3 style="margin-left:100px">Top Twitter HashTags Trending Now -- {{ name }}</h3>
{% elif country and not name %}
<h3 style="margin-left:100px">Top Twitter HashTags Trending Now -- {{ country }}</h3>
{% endif %}

{% if form %}
<form style="margin-left:100px" action="{% url 'geohash:ByMetro' %}" method="get">
  {{ form }}
  <input type="submit" value="Submit">
</form>
{% endif %}

<a style="margin-left:100px" href="{% url 'geohash:index' %}">Return to Homepage</a>

<body>
{% if d %}
<table style="background-color:#c7e1f0; width:350px; margin-top:35px; margin-left:100px" border="1" class="dataframe">
  <thead>
    <tr style="text-align: center;">
      <th>Rank</th>
      <th>HashTag</th>
      <th>TweetVol</th>
    </tr>
  </thead>
  <tbody>
  {% for k, v in d.items %}
  <tr>
    <td>{{ k }}</td>
    <td>{{ v.HashTag }}</td>
    <td style="text-align:right">{{ v.TweetVol }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}
</body>

steves_twitter_apps/geohash/templates/geohash/table_test_04.html
<body>
{% if d %}
<table style="background-color:#c7e1f0; width:350px; margin-top:35px; margin-left:100px" border="1" class="dataframe">
  <thead>
    <tr style="text-align: center;">
      <th>Rank</th>
      <th>HashTag</th>
      <th>TweetVol</th>
    </tr>
  </thead>
  <tbody>
  {% for k, v in d.items %}
  <tr>
    <td>{{ k }}</td>
    <td>{{ v.HashTag }}</td>
    <td style="text-align:right">{{ v.TweetVol }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}
</body>